### ISSUE TITLE
Considering the support for AWS Lambda?

### ISSUE THREAD

**Issue by fealone** [odd12258053/agraffe#1]
I'd be happy if could use AWS Lambda with agraffe, for programming without being aware of the environment.
Are you considering the support?

**Comment by odd12258053** [comment]
Thank you for your comment.
I don't consider it.
There are exists libraries to support AWS Lambda or Azure Functions.
But, Mangum and Bonnette are only supporting the service.
So, for usability, I will try to support other Serverless providers.

For AWS Lambda:
https://github.com/erm/mangum

For Azure Functions:
https://github.com/erm/bonnette

**Comment by odd12258053** [comment]
From version 0.2.0, Agraffe supports `AWS lambda` with API Gateway REST API.
I consider supporting Azure Functions in the next release.

If the update to 0.2.0, Agraffe requires a service name.
Please set the service name to 2nd argument in Agraffe.

For example;
```python
Agraffe(app, 'Google Cloud Functions')
```

If you want more examples, You see the `example` directory.
