### ISSUE TITLE
[GCP function]Support for request forms and files

### ISSUE THREAD

**Issue by jeremietharaud** [odd12258053/agraffe#13]
Hi,

Is it possible to add support for request forms and files as used in FastAPI ? [https://fastapi.tiangolo.com/tutorial/request-forms-and-files/](https://fastapi.tiangolo.com/tutorial/request-forms-and-files/)

Thank you.

**Comment by odd12258053** [comment]
@jeremietharaud 

Hi, jeremietharaud,
Thank you for your requests.

Agraffe, version is 0.5.0, will support request forms and files in Google Cloud Functions.

**Comment by odd12258053** [comment]
I tested in Google Cloud Functions. And AWS, Azure.

**Comment by odd12258053** [comment]
@jeremietharaud 

Agraffe 0.5.0, support request forms and files in Google Cloud Functions.
Please update Agraffe and check this request.

**Comment by jeremietharaud** [comment]
Thank you, it's working fine.
